export const ACTION_TYPE = {
  INCREMENT_COUNT: "INCREMENT_COUNT",
  INCREMENT_COUNT_TEN: "INCREMENT_COUNT_TEN",
  DOUBLE_COUNT: "DOUBLE_COUNT",
  DECREMENT_COUNT_TEN: "DECREMENT_COUNT_TEN",
  DECREMENT_COUNT: "DECREMENT_COUNT",
  RESET_COUNT: "RESET_COUNT",
};
